sudo: false
language: node_js
node_js:
  - "4.2.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
rvm:
  - 2.1.7
cache:
  directories:
    - node_modules
    - vendor/bundle
before_install:
  - npm install -g grunt-cli
  - gem update --system && gem install scss_lint -v 0.43.2
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
notifications:
  slack:
    secure: kAmrLltV0ZLuhl6rKk26fDLGuoCch6AYaObRQje4UZlxVQjR2467k430vOZLqv39Mr3U5XmYl6VLcCGmBr3tjM/9c1zjoXnRT8MRy4eIYaUr/thXeh2FlfHKOk8rXnNOoRZ1kBsCzCDFCNDYZZA4jya8S5ITcQyGyYcOqBWVy1w=
